### PR TITLE
Fix AV1/VP9 (and send/receive API use in general)

### LINKED ISSUE #319: Re-Visit VP9
Our parser is now incorrect as of https://github.com/FFmpeg/FFmpeg/commit/0c162854c1fa2a1e43ce5588b67842675f45e3c7.

For versions before `0c162854c1fa2a1e43ce5588b67842675f45e3c7`, we need to keep `ParseVP9`, but for versions after, it is incorrect: It marks any superframes as invisible, because they contain both a visible and invisible frame. There of course was no version bump at all of this breaking change.

Furthermore, the way we are calling `avcodec_send_packet` and `avcodec_receieve_frame`, while correct according the libavcodec documentation, is not correct in pratice, because apparently when the VP9 sueprframe bistream filter is inserted internally (completely hidden from us, this is internal to avcodec), it doesn't seem to properly buffer the full superframe packet. So if we do as we currently do, and call `avcodec_send_packet()` followed by `avcodec_receive_frame()` until we get a frame output, it will lead to silent corruption of the output frame, since the whole superframe packet is not being consumed. According to @wm4, this *should* work, but instead, as a workaround, we should be able call `avcodec_receive_frame()` in a loop (in practice, just a second time), until it returns `AVERROR(EAGAIN)`, rather than stopping when we get a frame.

### LINKED ISSUE #352: VP9 decodes to scrambled video after fefe4b97
Original issue: https://github.com/wangqr/Aegisub/issues/32
Test video: https://youtu.be/MNcnT8wBcdw or https://ftp.wangqr.tk/tmp/%E5%BF%83%E5%81%9A%E3%81%97%20_%20%E5%A4%8F%E8%89%B2%E3%81%BE%E3%81%A4%E3%82%8A%20cover%E3%80%90%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%ABPV_4K%E3%80%91-MNcnT8wBcdw.webm (both links are the same video, latter may be deleted shortly after)

This is a regression bug, which does not present in 2.23.1 release. git bisect shows that fefe4b979d3e04de8dc3383be4f85e3778d4ae6d is the first bad commit.
```
fefe4b979d3e04de8dc3383be4f85e3778d4ae6d is the first bad commit
commit fefe4b979d3e04de8dc3383be4f85e3778d4ae6d
Author: myrsloik <fredrik.mellbin@gmail.com>
Date:   Mon Mar 27 14:25:01 2017 +0200

    Add back original videosource hacks

 src/core/videosource.cpp | 32 ++++++++++++++++++++++++++------
 src/core/videosource.h   |  4 ++++
 2 files changed, 30 insertions(+), 6 deletions(-)
```

Screenshot

### PR DESCRIPTION
**Pull request by dwbuiten**
This PR does two things:
* Properly sets the delay when AV1 is being decoded, which is possible since FFmpeg/FFmpeg@1b05d27346130599ea188c35f97790d95db1d55f. We can make this slightly more generic to all codecs, but I want to change that later in a separate change set so as to keep any introduced bugs separate.
* Properly handles `AVERROR(EAGAIN)` from `avcodec_send_packet` by stashing the packet to send again on the next call, and from `avcodec_receive_frame` by increasing the delay counter.

Since this makes changes to the core decode loop(s), it needs some good testing before merging. Particularily to confiirm AV1 and VP9 are, in fact, fixed (seeking, and linear).

Should (probably) fix #319, and makes #323 obsolete, I *think*. May or may not fix #352.

CC: @tdaede @jamrial @wangqr

### CODE REVIEW

**Comment by myrsloik** [comment]
Looks reasonable, will try on some random av1 files later

File: src/core/videosource.cpp [hunk 1]
```diff
@@ -241,10 +242,19 @@ FFMS_VideoSource::FFMS_VideoSource(const char *SourceFile, FFMS_Index &Index, in
...
-        if (CodecContext->codec_id == AV_CODEC_ID_VC1 && CodecContext->has_b_frames)
+        if (CodecContext->codec_id == AV_CODEC_ID_VC1 && CodecContext->has_b_frames) {
             Delay = 7 + (CodecContext->thread_count - 1); // the maximum possible value for vc1
-        else
+        } else if (CodecContext->codec_id == AV_CODEC_ID_AV1) {
+#if VERSION_CHECK(LIBAVCODEC_VERSION_INT, >=, 60, 14, 101)
+            // libdav1d.c exports delay like this.
+            Delay = CodecContext->delay;
+#else
+            Delay = 0; // Welp, nothing we can do.
```
Comment (tdaede) [inline src/core/videosource.cpp:252]: Would it be better just to fail AV1 in this case? Seems like that might allow problems to be detected sooner than exporting corrupted frames.

File: src/core/videosource.cpp [hunk 2]
```diff
@@ -241,10 +242,19 @@ FFMS_VideoSource::FFMS_VideoSource(const char *SourceFile, FFMS_Index &Index, in
         // vc1 simply sets has_b_frames to 1 no matter how many there are so instead we set it to the max value
         // in order to not confuse our own delay guesses later
         // Doesn't affect actual vc1 reordering unlike h264
-        if (CodecContext->codec_id == AV_CODEC_ID_VC1 && CodecContext->has_b_frames)
+        if (CodecContext->codec_id == AV_CODEC_ID_VC1 && CodecContext->has_b_frames) {
             Delay = 7 + (CodecContext->thread_count - 1); // the maximum possible value for vc1
-        else
+        } else if (CodecContext->codec_id == AV_CODEC_ID_AV1) {
+#if VERSION_CHECK(LIBAVCODEC_VERSION_INT, >=, 60, 14, 101)
+            // libdav1d.c exports delay like this.
```
Comment (tdaede) [inline src/core/videosource.cpp:249]: It looks like libaom.c does not. Does it work without delay?

File: src/core/videosource.cpp [hunk 3]
```diff
@@ -633,12 +643,19 @@ bool FFMS_VideoSource::HasPendingDelayedFrames() {
...
 bool FFMS_VideoSource::DecodePacket(AVPacket *Packet) {
     std::swap(DecodeFrame, LastDecodedFrame);
-    avcodec_send_packet(CodecContext, Packet);
+    ResendPacket = false;
 
-    int Ret = avcodec_receive_frame(CodecContext, DecodeFrame);
+    int Ret = avcodec_send_packet(CodecContext, Packet);
+    if (Ret == AVERROR(EAGAIN)) {
+        // Send queue is full, so stash packet to resend on the next call.
+        DelayCounter--;
```
Comment (tdaede) [inline src/core/videosource.cpp:651]: If we can delay more than once, shouldn't the stashed packet be a stash queue?

File: src/core/videosource.cpp (hunk 2 above)
Comment (jamrial) [reply src/core/videosource.cpp:249]: libaom doesn't have delay given it doesn't implement frame threading or buffering internally.

File: src/core/videosource.cpp [hunk 4]
```diff
@@ -241,10 +242,19 @@ FFMS_VideoSource::FFMS_VideoSource(const char *SourceFile, FFMS_Index &Index, in
...
-        else
+        } else if (CodecContext->codec_id == AV_CODEC_ID_AV1) {
+#if VERSION_CHECK(LIBAVCODEC_VERSION_INT, >=, 60, 14, 101)
+            // libdav1d.c exports delay like this.
+            Delay = CodecContext->delay;
+#else
+            Delay = 0; // Welp, nothing we can do.
+#endif
+        } else {
+            // In theory we can move this to CodecCodentext->delay, sort of, one day, maybe. Not now.
```
Comment (rzumer) [inline src/core/videosource.cpp:255]:
```suggestion
            // In theory we can move this to CodecContext->delay, sort of, one day, maybe. Not now.
```

File: src/core/videosource.cpp (hunk 1 above)
Comment (dwbuiten) [reply src/core/videosource.cpp:252]: @myrsloik opinion?

File: src/core/videosource.cpp (hunk 3 above)
Comment (dwbuiten) [reply src/core/videosource.cpp:651]: No, since we don't read another packet until the stashed one is successfully sent.

File: src/core/videosource.cpp (hunk 4 above)
Comment (dwbuiten) [reply src/core/videosource.cpp:255]: Will fix.

File: src/core/videosource.cpp (hunk 1 above)
Comment (myrsloik) [reply src/core/videosource.cpp:252]: > @myrsloik opinion?
I'd simply print a warning or something. It's not worse than before. If we're lucky this process will drag long enough for FFmpeg 6.1 (I guess?) to be released and we could require it. Or did I misunderstand the problem?

**Comment by dwbuiten** [comment]
> Anything I can do to help move this along? I'm looking at getting a new Aegisub stable out but I'd like to have proper VP9/AV1 support, and don't want to build against a fork.

Mostly it is a function of my time (of which I have little at the moment...) - the current PR seems to have issues, which I need to debug.

**Comment by L4cache** [comment]
How about using libvpx to decode vp9? It seems faster than native one and with support of alpha channel in addition.

**Comment by L4cache** [comment]
I encountered this error opening files with video+audio with several combination of codecs after this PR.
vapoursynth.Error: Source: Insanity detected: decoder returned an empty frame

**Comment by L4cache** [comment]
> @L4cache I am revisiting this PR currently, can you provide an example file?

https://transfer.sh/85oyj7LBrm/sample.zip

**Comment by dwbuiten** [comment]
@L4cache Thanks, I was able to reproduce the issue using your sample. I will look into it.

**Comment by dwbuiten** [comment]
@L4cache I found the bug. I have updated the PR.

**Comment by dwbuiten** [comment]
Merged, let the testing begin!

Note thay CI failed for unrelated reasons. Tests pass locally, aside from HDR metadata which is being fixed upstream in FFmpeg right now.
